// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwKQtYk7CI-ZVN9hRZrppJ1P17PKuwuFI',
    appId: '1:913984649055:web:183a03341841ff235e68ea',
    messagingSenderId: '913984649055',
    projectId: 'darttzap',
    authDomain: 'darttzap.firebaseapp.com',
    storageBucket: 'darttzap.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2v4Qb9c7bHWxlDO2YpilEoyyntMWd7Ok',
    appId: '1:913984649055:android:5ebd5c35616ea5445e68ea',
    messagingSenderId: '913984649055',
    projectId: 'darttzap',
    storageBucket: 'darttzap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXbkpj_FZAtsyko3ABe7YYnjlJw9Jy17c',
    appId: '1:913984649055:ios:408cba16bf75be0a5e68ea',
    messagingSenderId: '913984649055',
    projectId: 'darttzap',
    storageBucket: 'darttzap.appspot.com',
    androidClientId: '913984649055-3n2thdl1bfr78liplbamf7gb50tfuef5.apps.googleusercontent.com',
    iosClientId: '913984649055-v8ikvte16t04kp5mvascecp0u2vvof1g.apps.googleusercontent.com',
    iosBundleId: 'yes',
  );
}
